s1:
  包头: aa55
  数据标志: bb
  枪械类型: 1
  子弹数量: 10
  校验和: cc
  包尾: 55aa
s2:
  包头: aa55
  数据标志: bb
  枪械类型: 1
  子弹数量: 1
  校验和: bd
  包尾: 55aa
s3:
  包头: aa55
  数据标志: bb
  枪械类型: 1
  子弹数量: 20
  校验和: dc
  包尾: 55aa
s4:
  包头: aa55
  数据标志: bb
  枪械类型: 2
  子弹数量: 10
  校验和: cd
  包尾: 55aa
s5:
  包头: aa55
  数据标志: bb
  枪械类型: 2
  子弹数量: 1
  校验和: be
  包尾: 55aa
s6:
  包头: aa55
  数据标志: bb
  枪械类型: 2
  子弹数量: 20
  校验和: dd
  包尾: 55aa
s7:
  包头: aa55
  数据标志: bb
  枪械类型: 0
  子弹数量: 10
  校验和: cb
  包尾: 55aa
s8:
  包头: aa55
  数据标志: bb
  枪械类型: 0
  子弹数量: 1
  校验和: bc
  包尾: 55aa
s9:
  包头: aa55
  数据标志: bb
  枪械类型: 0
  子弹数量: 20
  校验和: db
  包尾: 55aa
s1:
  包头: aa55
  数据标志: bb
  枪械类型: 1
  子弹数量: 10
  校验和: cc
  包尾: 55aa
s2:
  包头: aa55
  数据标志: bb
  枪械类型: 1
  子弹数量: 1
  校验和: bd
  包尾: 55aa
s3:
  包头: aa55
  数据标志: bb
  枪械类型: 1
  子弹数量: 20
  校验和: dc
  包尾: 55aa
s4:
  包头: aa55
  数据标志: bb
  枪械类型: 2
  子弹数量: 10
  校验和: cd
  包尾: 55aa
s5:
  包头: aa55
  数据标志: bb
  枪械类型: 2
  子弹数量: 1
  校验和: be
  包尾: 55aa
s6:
  包头: aa55
  数据标志: bb
  枪械类型: 2
  子弹数量: 20
  校验和: dd
  包尾: 55aa
s7:
  包头: aa55
  数据标志: bb
  枪械类型: 0
  子弹数量: 10
  校验和: cb
  包尾: 55aa
s8:
  包头: aa55
  数据标志: bb
  枪械类型: 0
  子弹数量: 1
  校验和: bc
  包尾: 55aa
s9:
  包头: aa55
  数据标志: bb
  枪械类型: 0
  子弹数量: 20
  校验和: db
  包尾: 55aa
